version: "3.5"
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: unless-stopped
    hostname: ${GITLAB_HOST}
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://${GITLAB_HOST}:9090'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        gitlab_rails['gitlab_default_projects_features_container_registry'] = true
        registry['enable'] = true
        registry_external_url 'http://${GITLAB_HOST}:4567'
    ports:
      - '9090:9090'
      - '2224:22'
      - '4567:4567'
    volumes:
      - '${GITLAB_PATH}/config:/etc/gitlab'
      - '${GITLAB_PATH}/gitlab/logs:/var/log/gitlab'
      - '${GITLAB_PATH}/gitlab/data:/var/opt/gitlab'
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    restart: unless-stopped
    volumes:
      - ${GITLAB_RUNNER_PATH}/config:/etc/gitlab-runner
      - ${GITLAB_RUNNER_PATH}/run:/var/run
     