version: "3.5"
services:
  gitlab.example.com:
    image: 'gitlab/gitlab-ce:latest'
    restart: unless-stopped
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://${GITLAB_HOST}:9090'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        gitlab_rails['gitlab_default_projects_features_container_registry'] = true
        registry['enable'] = true
        registry_external_url 'http://${GITLAB_HOST}:4567'
    ports:
      - '9090:9090'
      - '2224:22'
      - '4567:4567'
    volumes:
      - '${GITLAB_PATH}/config:/etc/gitlab'
      - '${GITLAB_PATH}/gitlab/logs:/var/log/gitlab'
      - '${GITLAB_PATH}/gitlab/data:/var/opt/gitlab'
    networks:
     gitlabWorkshop:
       ipv4_address: 172.24.0.2
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    restart: unless-stopped
    volumes:
      - ${GITLAB_RUNNER_PATH}/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      gitlabWorkshop:
        ipv4_address: 172.24.0.3
networks:
  gitlabWorkshop:
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/16     
